#!/bin/bash

gethelp() {
	echo "usage: gitp [[-n] <commit message>][-f <ssh address>] [-h]"
	echo "	no arguments to pull"
	echo "	-n: no push (offline option)"
	echo "	-f: first commit"
	echo "	-h: help"
}

showstatus() {
	echo -e "\033[02;37m$1\033[0;39m"
}

while getopts n:f:h:s OPT
do
	case $OPT in
		n)	status="no_push"
			;;
		f)	status="first_commit"
			address=$OPTARG
			# echo $address
			if [ -z $address ]; then
				exit 1
			fi
			;;
		h)	status="help"
			gethelp
			exit 0
			;;
		s)	status="git_status"
			git status
			exit 0
			;;
		\?) status="unexpected_option"
			showstatus error
			gethelp
			exit 0
			;;
	esac
done

if [ $# -eq 0 ]; then
	# gethelp
	# exit 1
	showstatus pulling...
        git pull
	exit 0
elif test $status="no_push"; then
	commit_message=${@:2:($#-1)}
	git add -A
	showstatus committing...
	git commit -m "${commit_message}"
	exit 0
elif [ -z $status ]; then
	commit_message=$*
	showstatus pulling...
	git pull
	git add -A
	showstatus committing...
	git commit -m "${commit_message}"
	showstatus pushing...
	if [ ! -d "$HOME/.custom-commands/tmp" ]; then
		mkdir "$HOME/.custom-commands/tmp"
	fi
	# { git push 3>&2 2>&1 1>&3 | tee "$HOME/.custom-commands/tmp/gitp_error"; } 3>&2 2>&1 1>&3
	{ { git push 1>&3; } 2>&1 | tee "$HOME/.custom-commands/tmp/gitp_error" 1>&2; } 3>&1
	retry_cmd=`cat "$HOME/.custom-commands/tmp/gitp_error" | grep 'git push --set-upstream origin'`
	# retry_cmd=`echo ${retry_cmd} | tr -d " "`
	retry_cmd=`echo ${retry_cmd} | sed -e "/^ /d"`
	eval "${retry_cmd}"
	# if [ -n ${retry_cmd} ]; then
	# 	showstatus retrying...
	# 	eval "${retry_cmd}"
	# fi
	rm "$HOME/.custom-commands/tmp/gitp_error"
	echo ''
	echo '✨ Done'
	exit 0
fi

if [ -n $address ]; then
	git init
	git add -A
	git commit -m "first commit"
	git remote add origin $address
	git push -u origin master
	exit 0
fi

# warning: push.default is unset; its implicit value has changed in
# Git 2.0 from 'matching' to 'simple'. To squelch this message
# and maintain the traditional behavior, use:

#   git config --global push.default matching

# To squelch this message and adopt the new behavior now, use:

#   git config --global push.default simple

# When push.default is set to 'matching', git will push local branches
# to the remote branches that already exist with the same name.

# Since Git 2.0, Git defaults to the more conservative 'simple'
# behavior, which only pushes the current branch to the corresponding
# remote branch that 'git pull' uses to update the current branch.

# See 'git help config' and search for 'push.default' for further information.
# (the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
# 'current' instead of 'simple' if you sometimes use older versions of Git)
